### ISSUE TITLE
Server Freeze bug for 10-15 seconds

### ISSUE THREAD

**Issue by nrliii** [HTTPStanley/DivinityEconomy#69]
**Describe the bug**
Running any of the commands after a server restarts/starts the first time a command is entered the server freezes a bit and it shows errors in console. That only happens once and doesnt happen until server restart

**To Reproduce**
1. Start the server
2. Enter for example /buy command and try buying something
3. Freeze happens for 10 seconds
4. Error which is attached to Additional Info shows up

**Expected behavior**
Would expect the server not to freeze for 10 seconds

**Screenshots**
![image](https://github.com/HTTPStanley/DivinityEconomy/assets/69441714/1fd8920d-c321-442f-88ec-7c1972db6770)
Image of console with timestamps. It freezes for 10 seconds and then it starts logging errors
**Context**
Server Version: 1.20.6
Server Type(Spigot/Paper): Paper
Additional Information:
https://pastebin.com/raw/0GQ8B6GK

**Comment by HTTPStanley** [comment]
Hi!

Thank you for posting. 

I understand that this issue is caused by the plugin interacting with materials older than the current version to support some legacy materials. The lag is not caused by DivinityEconomy, but by Spigot loading the Legacy Material Support. 

It's unusual that this would take more than 10 seconds, but I don't believe that's something I can personally fix without removing legacy materials from the plugin.

Cheers.

**Comment by nrliii** [comment]
Okay thank you very much for the fast reply!
